install:
  - choco install -y dart-sdk 7zip.commandline
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - pub get

  - appveyor DownloadFile "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/content_shell-linux-x64-release.zip"
  - 7z e content_shell-linux-x64-release.zip
  - rm content_shell-linux-x64-release.zip
  - move drt-win-full-stable-* content_shell
  - set PATH=%PATH%;%CD%\content_shell

build: off

test_script:
- pub run test -p vm,content_shell
