install:
  - choco install -y dart-sdk 7zip.commandline
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - pub get

  - appveyor DownloadFile "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/content_shell-windows-ia32-release.zip"
  - 7z e content_shell-windows-ia32-release.zip
  - rm content_shell-windows-ia32-release.zip
  - dir
  - ps: Rename-Item (Get-ChildItem drt-win-full-stable-*) content_shell
  - set PATH=%PATH%;%CD%\content_shell

  - content_shell.exe

build: off

test_script:
- pub run test -p vm,content-shell
